### ISSUE TITLE
esp32-c5 sdio slave (EHM-12)

### ISSUE THREAD

**Issue by skylin008** [espressif/esp-hosted-mcu#12]
Thank you for shared impressive project. I want to used wifi 2.4G/5G , the only esp32c5 compatible.So, I used the esp32-p4 chip for mcu host , and esp32c5 via sdio connected to esp32-p4 sdio port. How to esp32c5 sdio for sdio slave. Thanks!

**Comment by hmartin-hst** [comment]
Just received DEV Kit WT99P4C5-S1 from wireless tag, embedding a ESP32-C5-WROOM-1, has you mentionned I'm able to setup in QSPI, and works perfectly.  But is there a way to enable SDIO mode? 
From the ESP32-C5 slave I can configure it, but as soon as wifi_remote c5 is selected SDIO is not available anymore.

Edit: 
Found the answer, need to modify those 2 files:
- host/drivers/transport/sdio/sdio_reg.h:72 : 
  ```#if H_SLAVE_TARGET_ESP32 || H_SLAVE_TARGET_ESP32C6 || H_SLAVE_TARGET_ESP32C5```
- KConfig:30 :
 ```default y if (IDF_TARGET_ESP32 || IDF_TARGET_ESP32S3 || IDF_TARGET_ESP32P4) && (SLAVE_IDF_TARGET_ESP32 || SLAVE_IDF_TARGET_ESP32C6 || SLAVE_IDF_TARGET_ESP32C5 )```

**Comment by mantriyogesh** [comment]
### Clarification for Your Queries
This code is already on 'main' and includes the latest registry component. The commit that introduced these changes is https://github.com/espressif/esp-hosted-mcu/commit/7b347f7f547bcf66ec95384b9bb9609794586de4.

However, this commit is minimal; additional commits were made to ensure a smooth C5 with P4 experience.

I recommend using the latest version of the registry component https://components.espressif.com/components/espressif/esp_hosted.

### How to Use the Latest Component Version?
The code on the ESP-IDF **master** branch should automatically fetch the latest versions:

https://github.com/espressif/esp-idf/blob/9ddef27ed4a1587e3e8d4270881be9c3c4bc9241/examples/wifi/iperf/main/idf_component.yml#L10-L17

If you wish to mandatorily use the latest components for wifi-remote and esp-hosted, you can change to use `*`

```
  espressif/esp_wifi_remote:
    version: "*"
    rules:
      - if: "target in [esp32p4, esp32h2]"
  espressif/esp_hosted:
    version: "*"
    rules:
      - if: "target in [esp32p4, esp32h2]"
``` 

> [!NOTE]
> - C5 Eco 2 or greater
>   - Ensure you use C5 is of MP or `>= eco2` (looks like your case) 
>   - SDIO / SPI / DualSPI / QuadSPI
> - C5 Eco 1
>   - `eco1` of C5 doesn't support SDIO. other transports like SPI / DualSPI / QuadSPI should still work on eco1.
